name: Deploy para GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy com GitHub Pages
        uses: actions/deploy-pages@v4
